services:
  mysql:
    image: mysql:8.0-debian
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 5432:5432
      - 3306:3306
    restart: always
    networks:
      - spotiplot-network
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: spotiplot
      MYSQL_USER: spotiplot
    # command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - spotiplot-network


networks: 
  spotiplot-network:
    driver: bridge