services:
  mysql:
    image: mysql:8.0-oracle
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    networks:
      - spotiplot-network
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: spotiplot
      MYSQL_USER: spotiplot

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - spotiplot-network
    environment:
      ADMINER_DEFAULT_SERVER: mysql

  monitor:
    image: spotiplot_monitor
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./app/cache:/app/cache
    networks:
      - spotiplot-network
    environment:
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ["python", "-u", "monitor.py"]

networks:
  spotiplot-network:
    driver: bridge
